"""empty message

Revision ID: 02346e4302de
Revises: e5f4991c1203
Create Date: 2019-10-16 13:16:18.996685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02346e4302de'
down_revision = 'e5f4991c1203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_data_bank', sa.Column('a_e', sa.String(length=300), nullable=True))
    op.add_column('line_data_bank', sa.Column('main_e', sa.String(length=300), nullable=True))
    op.add_column('line_data_bank', sa.Column('z_e', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_data_bank', 'z_e')
    op.drop_column('line_data_bank', 'main_e')
    op.drop_column('line_data_bank', 'a_e')
    # ### end Alembic commands ###
