"""empty message

Revision ID: 08b2f1abf097
Revises: 4356fa5fde28
Create Date: 2020-03-20 11:23:03.791938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08b2f1abf097'
down_revision = '4356fa5fde28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('man_lines_domains', sa.Column('man_domains', sa.Integer(), nullable=False))
    op.drop_constraint('man_lines_domains_ibfk_1', 'man_lines_domains', type_='foreignkey')
    op.create_foreign_key(None, 'man_lines_domains', 'domains', ['man_domains'], ['id'])
    op.drop_column('man_lines_domains', 'domains')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('man_lines_domains', sa.Column('domains', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'man_lines_domains', type_='foreignkey')
    op.create_foreign_key('man_lines_domains_ibfk_1', 'man_lines_domains', 'domains', ['domains'], ['id'])
    op.drop_column('man_lines_domains', 'man_domains')
    # ### end Alembic commands ###
