"""empty message

Revision ID: 0d468a9bd5c3
Revises: fc42d36fd13b
Create Date: 2019-11-29 08:49:17.742166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d468a9bd5c3'
down_revision = 'fc42d36fd13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_supplier', sa.Column('biz', sa.Integer(), nullable=True))
    op.add_column('ip_supplier', sa.Column('customer_manager', sa.Integer(), nullable=True))
    op.add_column('ip_supplier', sa.Column('noc', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ip_supplier', 'contacts', ['noc'], ['id'])
    op.create_foreign_key(None, 'ip_supplier', 'contacts', ['customer_manager'], ['id'])
    op.create_foreign_key(None, 'ip_supplier', 'contacts', ['biz'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ip_supplier', type_='foreignkey')
    op.drop_constraint(None, 'ip_supplier', type_='foreignkey')
    op.drop_constraint(None, 'ip_supplier', type_='foreignkey')
    op.drop_column('ip_supplier', 'noc')
    op.drop_column('ip_supplier', 'customer_manager')
    op.drop_column('ip_supplier', 'biz')
    # ### end Alembic commands ###
