"""empty message

Revision ID: 110ab459fcd5
Revises: 176d81b38bfc
Create Date: 2019-09-27 09:54:14.348530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110ab459fcd5'
down_revision = '176d81b38bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_data_bank', sa.Column('platform', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'line_data_bank', 'platforms', ['platform'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'line_data_bank', type_='foreignkey')
    op.drop_column('line_data_bank', 'platform')
    # ### end Alembic commands ###
