"""empty message

Revision ID: 176d81b38bfc
Revises: 7053abb9873d
Create Date: 2019-09-27 09:47:35.368576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '176d81b38bfc'
down_revision = '7053abb9873d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_data_bank', 'domains')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_data_bank', sa.Column('domains', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True))
    op.drop_constraint(None, 'line_data_bank', type_='foreignkey')
    op.create_index('ix_line_data_bank_backbone_platform', 'line_data_bank', ['backbone_platform'], unique=False)
    op.drop_table('lines_domains')
    op.drop_index(op.f('ix_domains_platform'), table_name='domains')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.drop_table('platforms')
    # ### end Alembic commands ###
