"""empty message

Revision ID: 29aac3391919
Revises: d6e817a8f535
Create Date: 2019-12-04 23:11:12.993285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29aac3391919'
down_revision = 'd6e817a8f535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_supplier', sa.Column('operate_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_supplier', 'operate_time')
    # ### end Alembic commands ###
