"""empty message

Revision ID: 2a278ad16db9
Revises: 0d468a9bd5c3
Create Date: 2019-11-29 08:51:20.851555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a278ad16db9'
down_revision = '0d468a9bd5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_supplier', sa.Column('line_operator', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ip_supplier', 'users', ['line_operator'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ip_supplier', type_='foreignkey')
    op.drop_column('ip_supplier', 'line_operator')
    # ### end Alembic commands ###
