"""empty message

Revision ID: 32443e2a6828
Revises: cb3874f87568
Create Date: 2020-03-20 09:44:40.937179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32443e2a6828'
down_revision = 'cb3874f87568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platforms', sa.Column('type', sa.String(20), nullable=True))
    op.create_index(op.f('ix_platforms_type'), 'platforms', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platforms_type'), table_name='platforms')
    op.drop_column('platforms', 'type')
    op.drop_constraint(None, 'line_data_bank', type_='foreignkey')
    op.drop_index(op.f('ix_line_data_bank_MAN_platform'), table_name='line_data_bank')
    op.drop_column('line_data_bank', 'MAN_platform')
    op.drop_index(op.f('ix_interconnection_a_client_addr'), table_name='interconnection')
    op.drop_column('interconnection', 'a_client_addr')
    # ### end Alembic commands ###
