"""empty message

Revision ID: 3b56551d049c
Revises: c5a251c4ab90
Create Date: 2019-10-10 17:35:32.495539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b56551d049c'
down_revision = 'c5a251c4ab90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_data_bank', sa.Column('a_chain', sa.String(length=300), nullable=True))
    op.add_column('line_data_bank', sa.Column('z_chain', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_data_bank', 'z_chain')
    op.drop_column('line_data_bank', 'a_chain')
    # ### end Alembic commands ###
