"""empty message

Revision ID: 4356fa5fde28
Revises: 32443e2a6828
Create Date: 2020-03-20 11:17:02.041199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4356fa5fde28'
down_revision = '32443e2a6828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('man_lines_domains',
    sa.Column('lines', sa.Integer(), nullable=False),
    sa.Column('domains', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domains'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['lines'], ['line_data_bank.id'], ),
    sa.PrimaryKeyConstraint('lines', 'domains')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('man_lines_domains')
    # ### end Alembic commands ###
