"""empty message

Revision ID: 4c9dd90e82b2
Revises: 80921bb95d37
Create Date: 2019-11-21 13:44:15.250038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9dd90e82b2'
down_revision = '80921bb95d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_data_bank', sa.Column('sub_line_code', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_data_bank', 'sub_line_code')
    # ### end Alembic commands ###
