"""empty message

Revision ID: 520f3d8cdf88
Revises: f53097c1a027
Create Date: 2019-11-28 22:53:32.013770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520f3d8cdf88'
down_revision = 'f53097c1a027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_supplier', sa.Column('status', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_supplier', 'status')
    # ### end Alembic commands ###
