"""empty message

Revision ID: 5a2631417f88
Revises: 772aff7d4426
Create Date: 2019-11-24 20:21:11.268116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2631417f88'
down_revision = '772aff7d4426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_device_list_ip'), 'device_list', ['ip'], unique=True)
    op.drop_constraint('device_list_ibfk_3', 'device_list', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('device_list_ibfk_3', 'device_list', 'ip_manager', ['ip'], ['id'])
    op.drop_index(op.f('ix_device_list_ip'), table_name='device_list')
    # ### end Alembic commands ###
