"""empty message

Revision ID: 5a2f66914637
Revises: 71a2478dd76d
Create Date: 2019-10-21 15:04:29.154504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2f66914637'
down_revision = '71a2478dd76d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machineroom_list', sa.Column('lift', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machineroom_list', 'lift')
    # ### end Alembic commands ###
