"""empty message

Revision ID: 5ac5ae5b87a7
Revises: 29aac3391919
Create Date: 2019-12-06 10:29:20.875579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac5ae5b87a7'
down_revision = '29aac3391919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_manager', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ip_manager', 'ip_manager', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ip_manager', type_='foreignkey')
    op.drop_column('ip_manager', 'parent_id')
    # ### end Alembic commands ###
