"""empty message

Revision ID: 603b6c437f61
Revises: 
Create Date: 2019-09-18 16:19:21.859392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603b6c437f61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=True),
    sa.Column('interface', sa.String(length=10), nullable=True),
    sa.Column('sub_int', sa.String(length=5), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('mac', sa.String(length=30), nullable=True),
    sa.Column('bas_name', sa.String(length=20), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_interface'), 'account', ['interface'], unique=False)
    op.create_index(op.f('ix_account_mac'), 'account', ['mac'], unique=False)
    op.create_index(op.f('ix_account_sub_int'), 'account', ['sub_int'], unique=False)
    op.create_index(op.f('ix_account_username'), 'account', ['username'], unique=False)
    op.create_table('additional_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_id', sa.String(length=256), nullable=False),
    sa.Column('additional_info', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alarm_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=4096), nullable=True),
    sa.Column('content_md5', sa.String(length=32), nullable=True),
    sa.Column('alarm_type', sa.SmallInteger(), nullable=True),
    sa.Column('alarm_level', sa.SmallInteger(), nullable=True),
    sa.Column('state', sa.SmallInteger(), nullable=True),
    sa.Column('lastCallId', sa.String(length=128), nullable=True),
    sa.Column('calledTimes', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('call_group', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarm_record_call_group'), 'alarm_record', ['call_group'], unique=False)
    op.create_index(op.f('ix_alarm_record_content_md5'), 'alarm_record', ['content_md5'], unique=False)
    op.create_index(op.f('ix_alarm_record_lastCallId'), 'alarm_record', ['lastCallId'], unique=False)
    op.create_table('api_configure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=20), nullable=False),
    sa.Column('api_params', sa.String(length=100), nullable=False),
    sa.Column('api_params_value', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=30), nullable=False),
    sa.Column('area_desc', sa.String(length=200), nullable=True),
    sa.Column('area_machine_room', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_area_name'), 'area', ['area_name'], unique=False)
    op.create_table('area_machine_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('permit_machine_room', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_machine_room_area_id'), 'area_machine_room', ['area_id'], unique=False)
    op.create_table('call_record_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoneNum', sa.String(length=20), nullable=True),
    sa.Column('respCode', sa.String(length=10), nullable=True),
    sa.Column('callId', sa.String(length=40), nullable=True),
    sa.Column('createDateInResp', sa.String(length=15), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('call_group', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_record_detail_callId'), 'call_record_detail', ['callId'], unique=False)
    op.create_index(op.f('ix_call_record_detail_call_group'), 'call_record_detail', ['call_group'], unique=False)
    op.create_index(op.f('ix_call_record_detail_createDateInResp'), 'call_record_detail', ['createDateInResp'], unique=False)
    op.create_index(op.f('ix_call_record_detail_phoneNum'), 'call_record_detail', ['phoneNum'], unique=False)
    op.create_index(op.f('ix_call_record_detail_respCode'), 'call_record_detail', ['respCode'], unique=False)
    op.create_table('call_time_range',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('range_name', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('stop_time', sa.Time(), nullable=False),
    sa.Column('day_adjust', sa.Integer(), nullable=True),
    sa.Column('valid_alarm_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_city'), 'city', ['city'], unique=True)
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('duty_attended_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attended_time_name', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('stop_time', sa.Time(), nullable=False),
    sa.Column('day_adjust', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duty_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.Date(), nullable=True),
    sa.Column('userid', sa.String(length=100), nullable=False),
    sa.Column('attended_time_id', sa.SmallInteger(), nullable=False),
    sa.Column('duty_status', sa.SmallInteger(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IP', sa.String(length=48), nullable=False),
    sa.Column('netmask', sa.String(length=3), nullable=False),
    sa.Column('gateway', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_manager_IP'), 'ip_manager', ['IP'], unique=False)
    op.create_index(op.f('ix_ip_manager_netmask'), 'ip_manager', ['netmask'], unique=False)
    op.create_table('job_desc',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=20), nullable=True),
    sa.Column('job_desc', sa.String(length=100), nullable=True),
    sa.Column('alarm_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('pcap_order',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.String(length=20), nullable=False),
    sa.Column('login_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('question_description', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcap_order_account_id'), 'pcap_order', ['account_id'], unique=False)
    op.create_index(op.f('ix_pcap_order_login_name'), 'pcap_order', ['login_name'], unique=False)
    op.create_index(op.f('ix_pcap_order_username'), 'pcap_order', ['username'], unique=False)
    op.create_table('pcap_result',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('sysid', sa.String(length=100), nullable=True),
    sa.Column('pcap_order_id', sa.String(length=128), nullable=True),
    sa.Column('pcap_filepath', sa.String(length=200), nullable=True),
    sa.Column('r2d2_filepath', sa.String(length=200), nullable=True),
    sa.Column('result_description', sa.String(length=1024), nullable=True),
    sa.Column('speedtest', sa.String(length=50), nullable=True),
    sa.Column('pingtest', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcap_result_pcap_order_id'), 'pcap_result', ['pcap_order_id'], unique=False)
    op.create_index(op.f('ix_pcap_result_sysid'), 'pcap_result', ['sysid'], unique=False)
    op.create_table('pi_register',
    sa.Column('sysid', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('times', sa.Integer(), nullable=True),
    sa.Column('last_register_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('sysid')
    )
    op.create_index(op.f('ix_pi_register_username'), 'pi_register', ['username'], unique=False)
    op.create_table('pon_alarm_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('frame', sa.String(length=2), nullable=True),
    sa.Column('slot', sa.String(length=2), nullable=True),
    sa.Column('port', sa.String(length=3), nullable=True),
    sa.Column('ontid', sa.String(length=3), nullable=True),
    sa.Column('fail_times', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('last_fail_time', sa.DateTime(), nullable=True),
    sa.Column('last_recovery_time', sa.DateTime(), nullable=True),
    sa.Column('alarmed_flag', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('snmp_interface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('snmp_sysname', sa.String(length=100), nullable=True),
    sa.Column('snmp_if_desc', sa.String(length=50), nullable=True),
    sa.Column('snmp_if_alias', sa.String(length=200), nullable=True),
    sa.Column('snmp_if_physical_status', sa.SmallInteger(), nullable=True),
    sa.Column('snmp_if_protocal_status', sa.SmallInteger(), nullable=True),
    sa.Column('snmp_last_down_time', sa.DateTime(), nullable=True),
    sa.Column('snmp_last_rec_time', sa.DateTime(), nullable=True),
    sa.Column('snmp_last_in_speed', sa.Float(), nullable=True),
    sa.Column('snmp_last_out_speed', sa.Float(), nullable=True),
    sa.Column('data_storage', sa.String(length=100), nullable=True),
    sa.Column('data_path', sa.String(length=100), nullable=True),
    sa.Column('snmp_last_fetch_status', sa.String(length=100), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snmp_interface_device_id'), 'snmp_interface', ['device_id'], unique=False)
    op.create_index(op.f('ix_snmp_interface_snmp_if_desc'), 'snmp_interface', ['snmp_if_desc'], unique=False)
    op.create_table('snmp_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=100), nullable=True),
    sa.Column('oid_name', sa.String(length=50), nullable=True),
    sa.Column('oid', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snmp_models_vendor'), 'snmp_models', ['vendor'], unique=False)
    op.create_table('syslog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility', sa.String(length=20), nullable=True),
    sa.Column('serverty', sa.String(length=20), nullable=True),
    sa.Column('device_ip', sa.String(length=40), nullable=True),
    sa.Column('logmsg', sa.String(length=600), nullable=True),
    sa.Column('logtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syslog_alarm_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_type', sa.String(length=10), nullable=True),
    sa.Column('alarm_name', sa.String(length=100), nullable=True),
    sa.Column('alarm_level', sa.String(length=10), nullable=True),
    sa.Column('alarm_status', sa.SmallInteger(), nullable=True),
    sa.Column('alarm_keyword', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_record',
    sa.Column('unique_id', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('expire', sa.String(length=10), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('ups_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oid_dict', sa.String(length=200), nullable=True),
    sa.Column('ip', sa.String(length=24), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('vendeor', sa.String(length=20), nullable=True),
    sa.Column('community', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vlan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=5), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('desc', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['vlan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vlan_name'), 'vlan', ['name'], unique=False)
    op.create_index(op.f('ix_vlan_type'), 'vlan', ['type'], unique=False)
    op.create_table('voice_notify_callback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoneNum', sa.String(length=15), nullable=True),
    sa.Column('state', sa.String(length=5), nullable=True),
    sa.Column('callId', sa.String(length=40), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_notify_callback_phoneNum'), 'voice_notify_callback', ['phoneNum'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_contact_name', sa.String(length=50), nullable=True),
    sa.Column('biz_contact_phoneNumber', sa.String(length=50), nullable=True),
    sa.Column('biz_contact_email', sa.String(length=50), nullable=True),
    sa.Column('biz_contact_address', sa.String(length=50), nullable=True),
    sa.Column('noc_contact_name', sa.String(length=50), nullable=True),
    sa.Column('noc_contact_phoneNumber', sa.String(length=50), nullable=True),
    sa.Column('noc_contact_email', sa.String(length=50), nullable=True),
    sa.Column('noc_contact_address', sa.String(length=50), nullable=True),
    sa.Column('customer_manager_name', sa.String(length=50), nullable=True),
    sa.Column('customer_manager_phoneNumber', sa.String(length=50), nullable=True),
    sa.Column('company', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company'), 'contacts', ['company'], unique=False)
    op.create_table('dns_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dns', sa.String(length=48), nullable=False),
    sa.Column('dns_role', sa.String(length=10), nullable=True),
    sa.Column('IPs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['IPs'], ['ip_manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_manager_dns'), 'dns_manager', ['dns'], unique=False)
    op.create_table('machineroom_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('city', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('permit_value', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['city'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_machineroom_list_city'), 'machineroom_list', ['city'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phoneNum', sa.String(length=15), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('duty', sa.Integer(), nullable=True),
    sa.Column('permit_machine_room', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['area'], ['area.id'], ),
    sa.ForeignKeyConstraint(['duty'], ['job_desc.job_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phoneNum')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_permit_machine_room'), 'users', ['permit_machine_room'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('device_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=False),
    sa.Column('device_belong', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=16), nullable=True),
    sa.Column('login_method', sa.String(length=10), nullable=True),
    sa.Column('login_name', sa.String(length=20), nullable=True),
    sa.Column('login_password', sa.String(length=20), nullable=True),
    sa.Column('enable_password', sa.String(length=20), nullable=True),
    sa.Column('machine_room_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('community', sa.String(length=20), nullable=True),
    sa.Column('monitor_status', sa.SmallInteger(), nullable=True),
    sa.Column('monitor_fail_date', sa.DateTime(), nullable=True),
    sa.Column('monitor_rec_date', sa.DateTime(), nullable=True),
    sa.Column('mib_model', sa.SmallInteger(), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['device_belong'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['machine_room_id'], ['machineroom_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_name')
    )
    op.create_index(op.f('ix_device_list_community'), 'device_list', ['community'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('alarm_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.create_table('interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_name', sa.String(length=20), nullable=False),
    sa.Column('interface_desc', sa.String(length=100), nullable=True),
    sa.Column('interface_type', sa.String(length=10), nullable=True),
    sa.Column('odf', sa.String(length=10), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('interface_status', sa.Boolean(), nullable=True),
    sa.Column('interface_conf', sa.String(length=300), nullable=True),
    sa.Column('device', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device'], ['device_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interfaces_interface_name'), 'interfaces', ['interface_name'], unique=False)
    op.create_table('interconnection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=20), nullable=True),
    sa.Column('customer', sa.Integer(), nullable=True),
    sa.Column('pop_device', sa.Integer(), nullable=True),
    sa.Column('pop_interface', sa.Integer(), nullable=True),
    sa.Column('odf_info', sa.String(length=100), nullable=True),
    sa.Column('opposite_side_device', sa.String(length=100), nullable=True),
    sa.Column('interface_uptime', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['pop_device'], ['device_list.id'], ),
    sa.ForeignKeyConstraint(['pop_interface'], ['interfaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interconnection_customer'), 'interconnection', ['customer'], unique=False)
    op.create_index(op.f('ix_interconnection_pop_device'), 'interconnection', ['pop_device'], unique=False)
    op.create_index(op.f('ix_interconnection_pop_interface'), 'interconnection', ['pop_interface'], unique=False)
    op.create_table('line_data_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_code', sa.String(length=50), nullable=True),
    sa.Column('customer', sa.Integer(), nullable=False),
    sa.Column('contacts', sa.Integer(), nullable=True),
    sa.Column('repair_code', sa.String(length=20), nullable=True),
    sa.Column('product_type', sa.String(length=20), nullable=True),
    sa.Column('product_model', sa.String(length=20), nullable=True),
    sa.Column('line_status', sa.SmallInteger(), nullable=True),
    sa.Column('record_status', sa.SmallInteger(), nullable=True),
    sa.Column('a_client_addr', sa.String(length=200), nullable=True),
    sa.Column('a_pop_interface', sa.Integer(), nullable=True),
    sa.Column('a_pop_type', sa.String(length=100), nullable=True),
    sa.Column('a_pop_interconnection', sa.Integer(), nullable=True),
    sa.Column('z_client_addr', sa.String(length=200), nullable=True),
    sa.Column('z_pop_interface', sa.Integer(), nullable=True),
    sa.Column('z_pop_type', sa.String(length=100), nullable=True),
    sa.Column('z_pop_interconnection', sa.Integer(), nullable=True),
    sa.Column('channel_type', sa.SmallInteger(), nullable=True),
    sa.Column('channel_number', sa.Integer(), nullable=True),
    sa.Column('channel_unit', sa.String(length=20), nullable=True),
    sa.Column('protect', sa.Boolean(), nullable=True),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('main_route', sa.String(length=300), nullable=True),
    sa.Column('backup_route', sa.String(length=300), nullable=True),
    sa.Column('line_operator', sa.Integer(), nullable=True),
    sa.Column('operate_time', sa.DateTime(), nullable=True),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['a_pop_interconnection'], ['interconnection.id'], ),
    sa.ForeignKeyConstraint(['a_pop_interface'], ['interfaces.id'], ),
    sa.ForeignKeyConstraint(['contacts'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['customer'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['line_operator'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vlan'], ['vlan.id'], ),
    sa.ForeignKeyConstraint(['z_pop_interconnection'], ['interconnection.id'], ),
    sa.ForeignKeyConstraint(['z_pop_interface'], ['interfaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_code')
    )
    op.create_index(op.f('ix_line_data_bank_a_pop_interface'), 'line_data_bank', ['a_pop_interface'], unique=False)
    op.create_index(op.f('ix_line_data_bank_customer'), 'line_data_bank', ['customer'], unique=False)
    op.create_index(op.f('ix_line_data_bank_line_status'), 'line_data_bank', ['line_status'], unique=False)
    op.create_index(op.f('ix_line_data_bank_product_model'), 'line_data_bank', ['product_model'], unique=False)
    op.create_index(op.f('ix_line_data_bank_product_type'), 'line_data_bank', ['product_type'], unique=False)
    op.create_index(op.f('ix_line_data_bank_vlan'), 'line_data_bank', ['vlan'], unique=False)
    op.create_index(op.f('ix_line_data_bank_z_pop_interface'), 'line_data_bank', ['z_pop_interface'], unique=False)
    op.create_table('cloud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cloud_provider', sa.String(length=10), nullable=False),
    sa.Column('cloud_accesspoint', sa.String(length=50), nullable=False),
    sa.Column('cloud_accesspoint_desc', sa.String(length=200), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['line_data_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_cloud_accesspoint'), 'cloud', ['cloud_accesspoint'], unique=False)
    op.create_index(op.f('ix_cloud_cloud_provider'), 'cloud', ['cloud_provider'], unique=False)
    op.create_table('dia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ip'], ['ip_manager.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['line_data_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mpls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_protocal', sa.String(length=20), nullable=True),
    sa.Column('as_number', sa.SmallInteger(), nullable=True),
    sa.Column('access_way', sa.String(length=10), nullable=True),
    sa.Column('vrf', sa.String(length=10), nullable=True),
    sa.Column('rt', sa.String(length=10), nullable=True),
    sa.Column('l3_interface', sa.Integer(), nullable=True),
    sa.Column('ip', sa.Integer(), nullable=True),
    sa.Column('local_route', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ip'], ['ip_manager.id'], ),
    sa.ForeignKeyConstraint(['l3_interface'], ['interfaces.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['line_data_bank.id'], ),
    sa.ForeignKeyConstraint(['local_route'], ['ip_manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpls_ip'), 'mpls', ['ip'], unique=False)
    op.create_index(op.f('ix_mpls_local_route'), 'mpls', ['local_route'], unique=False)
    op.create_table('wave_rent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wave', sa.String(length=10), nullable=False),
    sa.Column('route', sa.String(length=300), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['line_data_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wave_rent')
    op.drop_index(op.f('ix_mpls_local_route'), table_name='mpls')
    op.drop_index(op.f('ix_mpls_ip'), table_name='mpls')
    op.drop_table('mpls')
    op.drop_table('dia')
    op.drop_index(op.f('ix_cloud_cloud_provider'), table_name='cloud')
    op.drop_index(op.f('ix_cloud_cloud_accesspoint'), table_name='cloud')
    op.drop_table('cloud')
    op.drop_index(op.f('ix_line_data_bank_z_pop_interface'), table_name='line_data_bank')
    op.drop_index(op.f('ix_line_data_bank_vlan'), table_name='line_data_bank')
    op.drop_index(op.f('ix_line_data_bank_product_type'), table_name='line_data_bank')
    op.drop_index(op.f('ix_line_data_bank_product_model'), table_name='line_data_bank')
    op.drop_index(op.f('ix_line_data_bank_line_status'), table_name='line_data_bank')
    op.drop_index(op.f('ix_line_data_bank_customer'), table_name='line_data_bank')
    op.drop_index(op.f('ix_line_data_bank_a_pop_interface'), table_name='line_data_bank')
    op.drop_table('line_data_bank')
    op.drop_index(op.f('ix_interconnection_pop_interface'), table_name='interconnection')
    op.drop_index(op.f('ix_interconnection_pop_device'), table_name='interconnection')
    op.drop_index(op.f('ix_interconnection_customer'), table_name='interconnection')
    op.drop_table('interconnection')
    op.drop_index(op.f('ix_interfaces_interface_name'), table_name='interfaces')
    op.drop_table('interfaces')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_device_list_community'), table_name='device_list')
    op.drop_table('device_list')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_permit_machine_room'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_machineroom_list_city'), table_name='machineroom_list')
    op.drop_table('machineroom_list')
    op.drop_index(op.f('ix_dns_manager_dns'), table_name='dns_manager')
    op.drop_table('dns_manager')
    op.drop_index(op.f('ix_contacts_company'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_voice_notify_callback_phoneNum'), table_name='voice_notify_callback')
    op.drop_table('voice_notify_callback')
    op.drop_index(op.f('ix_vlan_type'), table_name='vlan')
    op.drop_index(op.f('ix_vlan_name'), table_name='vlan')
    op.drop_table('vlan')
    op.drop_table('ups_info')
    op.drop_table('token_record')
    op.drop_table('syslog_alarm_config')
    op.drop_table('syslog')
    op.drop_index(op.f('ix_snmp_models_vendor'), table_name='snmp_models')
    op.drop_table('snmp_models')
    op.drop_index(op.f('ix_snmp_interface_snmp_if_desc'), table_name='snmp_interface')
    op.drop_index(op.f('ix_snmp_interface_device_id'), table_name='snmp_interface')
    op.drop_table('snmp_interface')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('pon_alarm_record')
    op.drop_index(op.f('ix_pi_register_username'), table_name='pi_register')
    op.drop_table('pi_register')
    op.drop_index(op.f('ix_pcap_result_sysid'), table_name='pcap_result')
    op.drop_index(op.f('ix_pcap_result_pcap_order_id'), table_name='pcap_result')
    op.drop_table('pcap_result')
    op.drop_index(op.f('ix_pcap_order_username'), table_name='pcap_order')
    op.drop_index(op.f('ix_pcap_order_login_name'), table_name='pcap_order')
    op.drop_index(op.f('ix_pcap_order_account_id'), table_name='pcap_order')
    op.drop_table('pcap_order')
    op.drop_table('job_desc')
    op.drop_index(op.f('ix_ip_manager_netmask'), table_name='ip_manager')
    op.drop_index(op.f('ix_ip_manager_IP'), table_name='ip_manager')
    op.drop_table('ip_manager')
    op.drop_table('duty_schedule')
    op.drop_table('duty_attended_time')
    op.drop_table('customer')
    op.drop_index(op.f('ix_city_city'), table_name='city')
    op.drop_table('city')
    op.drop_table('call_time_range')
    op.drop_index(op.f('ix_call_record_detail_respCode'), table_name='call_record_detail')
    op.drop_index(op.f('ix_call_record_detail_phoneNum'), table_name='call_record_detail')
    op.drop_index(op.f('ix_call_record_detail_createDateInResp'), table_name='call_record_detail')
    op.drop_index(op.f('ix_call_record_detail_call_group'), table_name='call_record_detail')
    op.drop_index(op.f('ix_call_record_detail_callId'), table_name='call_record_detail')
    op.drop_table('call_record_detail')
    op.drop_index(op.f('ix_area_machine_room_area_id'), table_name='area_machine_room')
    op.drop_table('area_machine_room')
    op.drop_index(op.f('ix_area_area_name'), table_name='area')
    op.drop_table('area')
    op.drop_table('api_configure')
    op.drop_index(op.f('ix_alarm_record_lastCallId'), table_name='alarm_record')
    op.drop_index(op.f('ix_alarm_record_content_md5'), table_name='alarm_record')
    op.drop_index(op.f('ix_alarm_record_call_group'), table_name='alarm_record')
    op.drop_table('alarm_record')
    op.drop_table('additional_info')
    op.drop_index(op.f('ix_account_username'), table_name='account')
    op.drop_index(op.f('ix_account_sub_int'), table_name='account')
    op.drop_index(op.f('ix_account_mac'), table_name='account')
    op.drop_index(op.f('ix_account_interface'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
