"""empty message

Revision ID: 69d25d48430c
Revises: 08b2f1abf097
Create Date: 2020-03-20 14:26:08.912804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69d25d48430c'
down_revision = '08b2f1abf097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'line_data_bank', 'platforms', ['MAN_platform_z'], ['id'])
    op.create_foreign_key(None, 'line_data_bank', 'platforms', ['MAN_platform_a'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_data_bank', sa.Column('MAN_platform', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'line_data_bank', type_='foreignkey')
    op.drop_constraint(None, 'line_data_bank', type_='foreignkey')
    op.create_foreign_key('line_data_bank_ibfk_13', 'line_data_bank', 'platforms', ['MAN_platform'], ['id'])
    op.create_index('ix_line_data_bank_MAN_platform', 'line_data_bank', ['MAN_platform'], unique=False)
    op.drop_index(op.f('ix_line_data_bank_MAN_platform_z'), table_name='line_data_bank')
    op.drop_index(op.f('ix_line_data_bank_MAN_platform_a'), table_name='line_data_bank')
    op.drop_column('line_data_bank', 'MAN_platform_z')
    op.drop_column('line_data_bank', 'MAN_platform_a')
    op.create_table('man_lines_domains',
    sa.Column('lines', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('man_domains', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lines'], ['line_data_bank.id'], name='man_lines_domains_ibfk_2'),
    sa.ForeignKeyConstraint(['man_domains'], ['domains.id'], name='man_lines_domains_ibfk_3'),
    sa.PrimaryKeyConstraint('lines'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('man_lines_domains_z')
    op.drop_table('man_lines_domains_a')
    # ### end Alembic commands ###
