"""empty message

Revision ID: 7053abb9873d
Revises: d43a565480a9
Create Date: 2019-09-26 21:36:46.263626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7053abb9873d'
down_revision = 'd43a565480a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_data_bank', sa.Column('backbone_platform', sa.String(length=10), nullable=True))
    op.add_column('line_data_bank', sa.Column('domains', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_line_data_bank_backbone_platform'), 'line_data_bank', ['backbone_platform'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_data_bank_backbone_platform'), table_name='line_data_bank')
    op.drop_column('line_data_bank', 'domains')
    op.drop_column('line_data_bank', 'backbone_platform')
    # ### end Alembic commands ###
