"""empty message

Revision ID: 71a2478dd76d
Revises: e879f0b5130a
Create Date: 2019-10-18 15:36:58.098574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a2478dd76d'
down_revision = 'e879f0b5130a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machineroom_list', sa.Column('noc_contact', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'machineroom_list', 'contacts', ['noc_contact'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'machineroom_list', type_='foreignkey')
    op.drop_column('machineroom_list', 'noc_contact')
    # ### end Alembic commands ###
