"""empty message

Revision ID: 71dc755a8a77
Revises: 5a2f66914637
Create Date: 2019-10-21 15:12:23.103056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71dc755a8a77'
down_revision = '5a2f66914637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machineroom_list', sa.Column('type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machineroom_list', 'type')
    # ### end Alembic commands ###
