"""empty message

Revision ID: 72aa32e24b84
Revises: 110ab459fcd5
Create Date: 2019-09-30 08:46:18.174682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72aa32e24b84'
down_revision = '110ab459fcd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_list', 'ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_list', sa.Column('ip', mysql.VARCHAR(collation='utf8_bin', length=16), nullable=True))
    # ### end Alembic commands ###
