"""empty message

Revision ID: 772aff7d4426
Revises: 8eef61ba6474
Create Date: 2019-11-23 19:45:25.704998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '772aff7d4426'
down_revision = '8eef61ba6474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mpls_ibfk_6', 'mpls', type_='foreignkey')
    op.drop_column('mpls', 'l2_interface')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpls', sa.Column('l2_interface', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('mpls_ibfk_6', 'mpls', 'interfaces', ['l2_interface'], ['id'])
    # ### end Alembic commands ###
