"""empty message

Revision ID: 80921bb95d37
Revises: 34d2d8d6312a
Create Date: 2019-11-19 09:32:19.814467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80921bb95d37'
down_revision = '34d2d8d6312a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'create_time')
    # ### end Alembic commands ###
