"""empty message

Revision ID: 8eef61ba6474
Revises: 6f20cd4baa71
Create Date: 2019-11-23 19:28:45.558905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8eef61ba6474'
down_revision = '6f20cd4baa71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpls', sa.Column('l2_interface', sa.Integer(), nullable=True))
    op.drop_constraint('mpls_ibfk_2', 'mpls', type_='foreignkey')
    op.create_foreign_key(None, 'mpls', 'interfaces', ['l2_interface'], ['id'])
    op.drop_column('mpls', 'l3_interface')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpls', sa.Column('l3_interface', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mpls', type_='foreignkey')
    op.create_foreign_key('mpls_ibfk_2', 'mpls', 'interfaces', ['l3_interface'], ['id'])
    op.drop_column('mpls', 'l2_interface')
    # ### end Alembic commands ###
