"""empty message

Revision ID: a1b761354c58
Revises: d47d6df1801d
Create Date: 2019-11-04 14:34:52.529703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b761354c58'
down_revision = 'd47d6df1801d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cutover_order', sa.Column('cutover_send_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cutover_order', 'cutover_send_date')
    # ### end Alembic commands ###
