"""empty message

Revision ID: b1c205cc3e86
Revises: 74efa1bb4ff1
Create Date: 2020-01-09 10:50:25.188020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1c205cc3e86'
down_revision = '74efa1bb4ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_list', 'device_name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               nullable=True)
    op.drop_index('device_name', table_name='device_list')
    op.drop_index('ix_ip_group_group_name', table_name='ip_group')
    op.drop_index('ix_ip_manager_desc', table_name='ip_manager')
    op.drop_index('ix_ip_manager_isp', table_name='ip_manager')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ip_manager_isp', 'ip_manager', ['isp'], unique=False)
    op.create_index('ix_ip_manager_desc', 'ip_manager', ['desc'], unique=False)
    op.create_index('ix_ip_group_group_name', 'ip_group', ['group_name'], unique=False)
    op.create_index('device_name', 'device_list', ['device_name'], unique=True)
    op.alter_column('device_list', 'device_name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               nullable=False)
    # ### end Alembic commands ###
