"""empty message

Revision ID: b5e4e1fe1421
Revises: efa0675d4860
Create Date: 2019-11-26 15:49:39.122248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5e4e1fe1421'
down_revision = 'efa0675d4860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ip_supplier', type_='foreignkey')
    op.alter_column('ip_supplier', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=100),
               nullable=True)
    # ### end Alembic commands ###
