"""empty message

Revision ID: bbb503e86fde
Revises: 72aa32e24b84
Create Date: 2019-09-30 08:48:32.522415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb503e86fde'
down_revision = '72aa32e24b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_list', sa.Column('ip', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'device_list', 'ip_manager', ['ip'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_list', type_='foreignkey')
    op.drop_column('device_list', 'ip')
    # ### end Alembic commands ###
