"""empty message

Revision ID: bdd4051d082d
Revises: 5ac5ae5b87a7
Create Date: 2019-12-06 16:57:38.846758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd4051d082d'
down_revision = '5ac5ae5b87a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dia', sa.Column('available_ip', sa.Integer(), nullable=True))
    op.add_column('dia', sa.Column('mode', sa.SmallInteger(), nullable=True))
    op.create_foreign_key(None, 'dia', 'ip_group', ['available_ip'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dia', type_='foreignkey')
    op.drop_column('dia', 'mode')
    op.drop_column('dia', 'available_ip')
    # ### end Alembic commands ###
