"""empty message

Revision ID: c1cc5dae3f50
Revises: 47550137dbb7
Create Date: 2019-11-23 19:06:58.176776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1cc5dae3f50'
down_revision = '47550137dbb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'mpls', 'ip_group', ['interconnect_ip'], ['id'])
    op.drop_column('mpls', 'local_route')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpls', sa.Column('local_route', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mpls', type_='foreignkey')
    op.create_foreign_key('mpls_ibfk_4', 'mpls', 'ip_manager', ['local_route'], ['id'])
    op.create_index('ix_mpls_local_route', 'mpls', ['local_route'], unique=False)
    op.drop_column('mpls', 'interconnect_ip')
    op.drop_constraint(None, 'ip_manager', type_='foreignkey')
    op.drop_column('ip_manager', 'ip_group')
    op.drop_table('ip_group')
    # ### end Alembic commands ###
