"""empty message

Revision ID: c39e4201d752
Revises: 5a2631417f88
Create Date: 2019-11-25 17:19:50.090543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39e4201d752'
down_revision = '5a2631417f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vxlan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bd', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['line_data_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vxlan')
    # ### end Alembic commands ###
