"""empty message

Revision ID: c5a251c4ab90
Revises: e70c2831a85b
Create Date: 2019-10-07 22:07:18.072107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5a251c4ab90'
down_revision = 'e70c2831a85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operate_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table', sa.String(length=20), nullable=True),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('old_field', sa.String(length=1000), nullable=True),
    sa.Column('new_field', sa.String(length=1000), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('mpls', sa.Column('route_protocol', sa.String(length=20), nullable=True))
    op.drop_column('mpls', 'route_protocal')
    op.add_column('posts', sa.Column('line_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'line_data_bank', ['line_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'line_id')
    op.add_column('mpls', sa.Column('route_protocal', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True))
    op.drop_column('mpls', 'route_protocol')
    op.drop_table('operate_log')
    # ### end Alembic commands ###
