"""empty message

Revision ID: cb3874f87568
Revises: 
Create Date: 2020-03-17 10:14:24.342539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb3874f87568'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_list', sa.Column('platform_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'device_list', 'platforms', ['platform_id'], ['id'])
    op.add_column('snmp_interface', sa.Column('snmp_if_protocol_status', sa.SmallInteger(), nullable=True))
    op.drop_column('snmp_interface', 'snmp_if_protocal_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snmp_interface', sa.Column('snmp_if_protocal_status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.drop_column('snmp_interface', 'snmp_if_protocol_status')
    op.drop_constraint(None, 'device_list', type_='foreignkey')
    op.drop_column('device_list', 'platform_id')
    # ### end Alembic commands ###
