"""empty message

Revision ID: cf1697b1e26e
Revises: bdd4051d082d
Create Date: 2019-12-10 16:30:44.408691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1697b1e26e'
down_revision = 'bdd4051d082d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_line_code_combine', 'line_data_bank', ['line_code', 'sub_line_code'])
    op.drop_index('line_code', table_name='line_data_bank')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('line_code', 'line_data_bank', ['line_code'], unique=True)
    op.drop_constraint('_line_code_combine', 'line_data_bank', type_='unique')
    # ### end Alembic commands ###
