"""empty message

Revision ID: d43a565480a9
Revises: 603b6c437f61
Create Date: 2019-09-19 10:26:29.818030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43a565480a9'
down_revision = '603b6c437f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_list', sa.Column('device_mac', sa.String(length=50), nullable=True))
    op.add_column('device_list', sa.Column('device_model', sa.String(length=50), nullable=True))
    op.add_column('device_list', sa.Column('os_version', sa.String(length=50), nullable=True))
    op.add_column('device_list', sa.Column('patch_version', sa.String(length=50), nullable=True))
    op.add_column('device_list', sa.Column('serial_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_list', 'serial_number')
    op.drop_column('device_list', 'patch_version')
    op.drop_column('device_list', 'os_version')
    op.drop_column('device_list', 'device_model')
    op.drop_column('device_list', 'device_mac')
    # ### end Alembic commands ###
