"""empty message

Revision ID: d47d6df1801d
Revises: 71dc755a8a77
Create Date: 2019-10-28 13:37:06.708447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47d6df1801d'
down_revision = '71dc755a8a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lines_cutoverorder',
    sa.Column('lines', sa.Integer(), nullable=False),
    sa.Column('cutoverorder', sa.String(50), nullable=True),
    sa.ForeignKeyConstraint(['cutoverorder'], ['cutover_order.id'], ),
    sa.ForeignKeyConstraint(['lines'], ['line_data_bank.id'], ),
    sa.PrimaryKeyConstraint('lines')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lines_cutoverorder')
    op.drop_table('cutover_order')
    op.drop_table('customer_mailtemplet')
    op.drop_index(op.f('ix_mail_templet_name'), table_name='mail_templet')
    op.drop_index(op.f('ix_mail_templet_attachment_path'), table_name='mail_templet')
    op.drop_table('mail_templet')
    # ### end Alembic commands ###
