"""empty message

Revision ID: d6e817a8f535
Revises: 2a278ad16db9
Create Date: 2019-11-29 22:26:59.992828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6e817a8f535'
down_revision = '2a278ad16db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dns_manager_ibfk_1', 'dns_manager', type_='foreignkey')
    op.drop_column('dns_manager', 'IPs')
    op.add_column('ip_manager', sa.Column('dns', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ip_manager', 'dns_manager', ['dns'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ip_manager', type_='foreignkey')
    op.drop_column('ip_manager', 'dns')
    op.add_column('dns_manager', sa.Column('IPs', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('dns_manager_ibfk_1', 'dns_manager', 'ip_manager', ['IPs'], ['id'])
    # ### end Alembic commands ###
