"""empty message

Revision ID: d82e2263a94d
Revises: b1c205cc3e86
Create Date: 2020-03-04 10:38:22.861883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82e2263a94d'
down_revision = 'b1c205cc3e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interfaces', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'interfaces', 'interfaces', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interfaces', type_='foreignkey')
    op.drop_column('interfaces', 'parent_id')
    # ### end Alembic commands ###
