"""empty message

Revision ID: db02fe5d6a74
Revises: cf1697b1e26e
Create Date: 2020-01-05 21:25:10.014080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db02fe5d6a74'
down_revision = 'cf1697b1e26e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_line_data_bank_a_client_addr'), 'line_data_bank', ['a_client_addr'], unique=False)
    op.create_index(op.f('ix_line_data_bank_channel_number'), 'line_data_bank', ['channel_number'], unique=False)
    op.create_index(op.f('ix_line_data_bank_channel_type'), 'line_data_bank', ['channel_type'], unique=False)
    op.create_index(op.f('ix_line_data_bank_channel_unit'), 'line_data_bank', ['channel_unit'], unique=False)
    op.create_index(op.f('ix_line_data_bank_line_code'), 'line_data_bank', ['line_code'], unique=False)
    op.create_index(op.f('ix_line_data_bank_protect'), 'line_data_bank', ['protect'], unique=False)
    op.create_index(op.f('ix_line_data_bank_record_status'), 'line_data_bank', ['record_status'], unique=False)
    op.create_index(op.f('ix_line_data_bank_sub_line_code'), 'line_data_bank', ['sub_line_code'], unique=False)
    op.create_index(op.f('ix_line_data_bank_z_client_addr'), 'line_data_bank', ['z_client_addr'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_data_bank_z_client_addr'), table_name='line_data_bank')
    op.drop_index(op.f('ix_line_data_bank_sub_line_code'), table_name='line_data_bank')
    op.drop_index(op.f('ix_line_data_bank_record_status'), table_name='line_data_bank')
    op.drop_index(op.f('ix_line_data_bank_protect'), table_name='line_data_bank')
    op.drop_index(op.f('ix_line_data_bank_line_code'), table_name='line_data_bank')
    op.drop_index(op.f('ix_line_data_bank_channel_unit'), table_name='line_data_bank')
    op.drop_index(op.f('ix_line_data_bank_channel_type'), table_name='line_data_bank')
    op.drop_index(op.f('ix_line_data_bank_channel_number'), table_name='line_data_bank')
    op.drop_index(op.f('ix_line_data_bank_a_client_addr'), table_name='line_data_bank')
    # ### end Alembic commands ###
