"""empty message

Revision ID: e5f4991c1203
Revises: 3b56551d049c
Create Date: 2019-10-12 09:37:45.259057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f4991c1203'
down_revision = '3b56551d049c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_data_bank', sa.Column('line_stop_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_data_bank', 'line_stop_time')
    # ### end Alembic commands ###
