"""empty message

Revision ID: e70c2831a85b
Revises: bbb503e86fde
Create Date: 2019-09-30 08:51:17.284885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70c2831a85b'
down_revision = 'bbb503e86fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_manager', sa.Column('desc', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_manager', 'desc')
    # ### end Alembic commands ###
