"""empty message

Revision ID: e879f0b5130a
Revises: 02346e4302de
Create Date: 2019-10-17 21:06:38.190981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e879f0b5130a'
down_revision = '02346e4302de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'noc_contact_email')
    op.drop_column('contacts', 'noc_contact_address')
    op.drop_column('contacts', 'customer_manager_name')
    op.drop_column('contacts', 'customer_manager_phoneNumber')
    op.drop_column('contacts', 'biz_contact_phoneNumber')
    op.drop_column('contacts', 'biz_contact_address')
    op.drop_column('contacts', 'biz_contact_name')
    op.drop_column('contacts', 'noc_contact_phoneNumber')
    op.drop_column('contacts', 'biz_contact_email')
    op.drop_column('contacts', 'noc_contact_name')
    op.add_column('line_data_bank', sa.Column('biz', sa.Integer(), nullable=True))
    op.add_column('line_data_bank', sa.Column('customer_manager', sa.Integer(), nullable=True))
    op.add_column('line_data_bank', sa.Column('noc', sa.Integer(), nullable=True))
    op.drop_constraint('line_data_bank_ibfk_3', 'line_data_bank', type_='foreignkey')
    op.create_foreign_key(None, 'line_data_bank', 'contacts', ['noc'], ['id'])
    op.create_foreign_key(None, 'line_data_bank', 'contacts', ['biz'], ['id'])
    op.create_foreign_key(None, 'line_data_bank', 'contacts', ['customer_manager'], ['id'])
    op.drop_column('line_data_bank', 'contacts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_data_bank', sa.Column('contacts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'line_data_bank', type_='foreignkey')
    op.drop_constraint(None, 'line_data_bank', type_='foreignkey')
    op.drop_constraint(None, 'line_data_bank', type_='foreignkey')
    op.create_foreign_key('line_data_bank_ibfk_3', 'line_data_bank', 'contacts', ['contacts'], ['id'])
    op.drop_column('line_data_bank', 'noc')
    op.drop_column('line_data_bank', 'customer_manager')
    op.drop_column('line_data_bank', 'biz')
    op.add_column('contacts', sa.Column('noc_contact_name', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.add_column('contacts', sa.Column('biz_contact_email', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.add_column('contacts', sa.Column('noc_contact_phoneNumber', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.add_column('contacts', sa.Column('biz_contact_name', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.add_column('contacts', sa.Column('biz_contact_address', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.add_column('contacts', sa.Column('company', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('biz_contact_phoneNumber', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.add_column('contacts', sa.Column('customer_manager_phoneNumber', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.add_column('contacts', sa.Column('customer_manager_name', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.add_column('contacts', sa.Column('noc_contact_address', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.add_column('contacts', sa.Column('noc_contact_email', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.create_foreign_key('contacts_ibfk_1', 'contacts', 'customer', ['company'], ['id'])
    op.create_index('ix_contacts_company', 'contacts', ['company'], unique=False)
    op.drop_column('contacts', 'type')
    op.drop_column('contacts', 'phoneNumber')
    op.drop_column('contacts', 'name')
    op.drop_column('contacts', 'email')
    op.drop_column('contacts', 'address')
    # ### end Alembic commands ###
