"""empty message

Revision ID: efa0675d4860
Revises: c39e4201d752
Create Date: 2019-11-26 14:58:31.414229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa0675d4860'
down_revision = 'c39e4201d752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('line_access_interface', sa.Integer(), nullable=True),
    sa.Column('mode', sa.SmallInteger(), nullable=True),
    sa.Column('interconnect_ip', sa.Integer(), nullable=True),
    sa.Column('available_ip', sa.Integer(), nullable=True),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('stop_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['available_ip'], ['ip_group.id'], ),
    sa.ForeignKeyConstraint(['interconnect_ip'], ['ip_manager.id'], ),
    sa.ForeignKeyConstraint(['line_access_interface'], ['interfaces.id'], ),
    sa.ForeignKeyConstraint(['vlan'], ['vlan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_supplier_line_code'), 'ip_supplier', ['line_code'], unique=True)
    op.create_index(op.f('ix_ip_supplier_name'), 'ip_supplier', ['name'], unique=False)
    op.add_column('ip_manager', sa.Column('available_ip', sa.String(length=500), nullable=True))
    op.add_column('ip_manager', sa.Column('isp', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_manager', 'isp')
    op.drop_column('ip_manager', 'available_ip')
    op.drop_index(op.f('ix_ip_supplier_name'), table_name='ip_supplier')
    op.drop_index(op.f('ix_ip_supplier_line_code'), table_name='ip_supplier')
    op.drop_table('ip_supplier')
    # ### end Alembic commands ###
