"""empty message

Revision ID: f53097c1a027
Revises: b5e4e1fe1421
Create Date: 2019-11-26 15:54:34.129629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53097c1a027'
down_revision = 'b5e4e1fe1421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_manager', sa.Column('available_ip', sa.String(length=500), nullable=True))
    op.add_column('ip_manager', sa.Column('isp', sa.String(length=100), nullable=True))
    op.add_column('ip_supplier', sa.Column('supplier_name', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ip_supplier_supplier_name'), 'ip_supplier', ['supplier_name'], unique=False)
    op.create_foreign_key(None, 'ip_supplier', 'customer', ['supplier_name'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ip_supplier', type_='foreignkey')
    op.drop_index(op.f('ix_ip_supplier_supplier_name'), table_name='ip_supplier')
    op.drop_column('ip_supplier', 'supplier_name')
    op.drop_column('ip_manager', 'isp')
    op.drop_column('ip_manager', 'available_ip')
    # ### end Alembic commands ###
