"""empty message

Revision ID: fc42d36fd13b
Revises: 520f3d8cdf88
Create Date: 2019-11-28 23:30:50.564425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc42d36fd13b'
down_revision = '520f3d8cdf88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_supplier', sa.Column('bandwidth', sa.Integer(), nullable=True))
    op.add_column('ip_supplier', sa.Column('bandwidth_unit', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_supplier', 'bandwidth_unit')
    op.drop_column('ip_supplier', 'bandwidth')
    # ### end Alembic commands ###
