"""empty message

Revision ID: ffe8d0bc974b
Revises: e8e96f10d82a
Create Date: 2019-11-17 14:36:34.665495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe8d0bc974b'
down_revision = 'e8e96f10d82a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dia', sa.Column('dns', sa.Integer(), nullable=True))
    op.add_column('dia', sa.Column('provider', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'dia', 'dns_manager', ['dns'], ['id'])
    op.add_column('line_data_bank', sa.Column('line_desc', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_data_bank', 'line_desc')
    op.drop_constraint(None, 'dia', type_='foreignkey')
    op.drop_column('dia', 'provider')
    op.drop_column('dia', 'dns')
    # ### end Alembic commands ###
